#! /bin/sh

# The clock might be wrong and we know that we need to update the icon
# cache so we just force it.

gtk-update-icon-cache -f /usr/share/icons/hicolor

if [ ! -d /media/mmc1/marxpaint ]
then
   mkdir /media/mmc1/marxpaint
fi

echo " Lets ask about the location"
maemo-select-menu-location marxpaint.desktop tana_fi_games

exit 0
